languageCode = "de"
title = "SwissCovid"

defaultContentLanguage = "de"
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
  description = "Get the App | SwissCovid"

[languages]
  [languages.de]
    weight = 1
    languageName = "DE"
  [languages.en]
    weight = 2
    languageName = "EN"
  [languages.fr]
    weight = 3
    languageName = "FR"
  [languages.it]
    weight = 4
    languageName = "IT"

[markup.goldmark.renderer]
  unsafe= true
