name: prod build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: false
          fetch-depth: 0 

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.78.2'
          extended: true

      - name: Build
        run: |
          hugo -b https://qr.swisscovid.ch -d build_prod --cleanDestinationDir --minify
          hugo -b https://qr-d.swisscovid.ch -d build_dev --cleanDestinationDir --minify
          hugo -b https://qr-t.swisscovid.ch -d build_test --cleanDestinationDir --minify
          hugo -b https://qr-a.swisscovid.ch -d build_abnahme --cleanDestinationDir --minify
        
      - name: Copy .well-known
        run: |
          cp -R .well-known/prod/.well-known build_prod
          cp -R .well-known/dev/.well-known build_dev
          cp -R .well-known/test/.well-known build_test
          cp -R .well-known/abnahme/.well-known build_abnahme

      - name: Zip Build Directories
        run: |
          (cd build_prod && zip -r ../prod.zip .)
          (cd build_dev && zip -r ../dev.zip .)
          (cd build_test && zip -r ../test.zip .)
          (cd build_abnahme && zip -r ../abnahme.zip .)