name: prod build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: false
          fetch-depth: 0 

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.78.2'
          extended: true

      - name: Build Prod
        run: hugo -b https://qr.swisscovid.ch -d build_prod --cleanDestinationDir --minify
        run: cp -R .well-known/prod/.well-known build_prod